=== PabloJGA97/Practica-sindicacio/catelegnovetats.dtd
<!ELEMENT rss (channel)>
<!ELEMENT channel (title, link, description, pubDate, dc:date, item+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT pubDate (#PCDATA)>
<!ELEMENT dc:date (#PCDATA)>
<!ELEMENT item (title, link, description, pubDate, guid, dc:creator, dc:date)>
<!ELEMENT guid (#PCDATA)>
<!ATTLIST guid isPermaLink CDATA #IMPLIED>
<!ELEMENT dc:creator (#PCDATA)>
<!ATTLIST rss xmlns:dc CDATA #FIXED "http://purl.org/dc/elements/1.1/">
<!ATTLIST rss xmlns:dc CDATA #FIXED "http://purl.org/dc/elements/1.1/">
<!ATTLIST rss version CDATA #REQUIRED>

=== PabloJGA97/Practica-sindicacio/catalegnovetats.xml
<!DOCTYPE rss SYSTEM "catelegnovetats.dtd">
<rss xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
    <channel>
    <title>rssPremsa</title>
    <link>https://www.diba.cat/web/sala-de-premsa/nota-de-premsa/-/journal/rss/553295/2596612?refererPlid=390764</link>
    <description>RSS del Servei de Premsa - Diputació de Barcelona</description>
    <pubDate>Fri, 09 Feb 2024 22:46:12 GMT</pubDate>
    <dc:date>2024-02-09T22:46:12Z</dc:date>
    <item>
    <title>Iniciades les obres de revestiment de cunetes a la BV-4025 i a la BV-4656</title>
    <link>https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405597752</link>
    <description/>
    <pubDate>Fri, 09 Feb 2024 10:49:00 GMT</pubDate>
    <guid isPermaLink="false">https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405597752</guid>
    <dc:creator>EDGAR MATA ROCA</dc:creator>
    <dc:date>2024-02-09T10:49:00Z</dc:date>
    </item>
    <item>
    <title>La Diputació de Barcelona obre una línia d’atenció als ajuntaments per a consultes sobre la sequera i les instal·lacions esportives</title>
    <link>https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405594256</link>
    <description/>
    <pubDate>Fri, 09 Feb 2024 10:22:00 GMT</pubDate>
    <guid isPermaLink="false">https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405594256</guid>
    <dc:creator>ALBERTO GARCIA MARTINEZ</dc:creator>
    <dc:date>2024-02-09T10:22:00Z</dc:date>
    </item>
    <item>
    <title>Sant Feliu de Llobregat avança cap a solucions de ciutat intel·ligent</title>
    <link>https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405594145</link>
    <description/>
    <pubDate>Fri, 09 Feb 2024 10:15:00 GMT</pubDate>
    <guid isPermaLink="false">https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405594145</guid>
    <dc:creator>EDGAR MATA ROCA</dc:creator>
    <dc:date>2024-02-09T10:15:00Z</dc:date>
    </item>
    <item>
    <title>L’Institut Europeu d’Administració Pública reconeix els serveis de transformació digital SeTDIBA de la Diputació de Barcelona com a pràctica d’excel·lència</title>
    <link>https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405587400</link>
    <description/>
    <pubDate>Fri, 09 Feb 2024 08:25:00 GMT</pubDate>
    <guid isPermaLink="false">https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405587400</guid>
    <dc:creator>SERGI RIBAS REBULL</dc:creator>
    <dc:date>2024-02-09T08:25:00Z</dc:date>
    </item>
    <item>
    <title>L’impacte econòmic directe generat pel turisme creix un 21% a la Destinació Barcelona el 2023</title>
    <link>https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405547643</link>
    <description/>
    <pubDate>Fri, 09 Feb 2024 08:00:00 GMT</pubDate>
    <guid isPermaLink="false">https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405547643</guid>
    <dc:creator>NURIA PELAEZ RODRIGUEZ</dc:creator>
    <dc:date>2024-02-09T08:00:00Z</dc:date>
    </item>
    <item>
    <title>La Diputació de Barcelona inverteix més de 408.000 euros en la instal·lació d’una planta fotovoltaica a una nau municipal a Santa Perpètua de Mogoda</title>
    <link>https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405564321</link>
    <description/>
    <pubDate>Thu, 08 Feb 2024 14:59:00 GMT</pubDate>
    <guid isPermaLink="false">https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405564321</guid>
    <dc:creator>DULCE NOMBRE VALERO GARCIA</dc:creator>
    <dc:date>2024-02-08T14:59:00Z</dc:date>
    </item>
    <item>
    <title>Presentació de dades del programa “Reempresa Mercats Municipals” per prevenir el tancament de parades als mercats de la província de Barcelona</title>
    <link>https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405407800</link>
    <description/>
    <pubDate>Thu, 08 Feb 2024 13:00:00 GMT</pubDate>
    <guid isPermaLink="false">https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405407800</guid>
    <dc:creator>NURIA PELAEZ RODRIGUEZ</dc:creator>
    <dc:date>2024-02-08T13:00:00Z</dc:date>
    </item>
    <item>
    <title>La Xarxa de Parcs Naturals de la Diputació de Barcelona ofereix prop de 300 activitats dins del programa ‘Passejades guiades’</title>
    <link>https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405539936</link>
    <description/>
    <pubDate>Thu, 08 Feb 2024 12:20:00 GMT</pubDate>
    <guid isPermaLink="false">https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405539936</guid>
    <dc:creator>MAR LOIRE GARCIA</dc:creator>
    <dc:date>2024-02-08T12:20:00Z</dc:date>
    </item>
    <item>
    <title>L’exposició ‘ReHabilitem’ es pot visitar a Castellar del Vallès fins al 8 de març</title>
    <link>https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405540488</link>
    <description/>
    <pubDate>Thu, 08 Feb 2024 11:22:00 GMT</pubDate>
    <guid isPermaLink="false">https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405540488</guid>
    <dc:creator>SUSANA BURGOS JOVER</dc:creator>
    <dc:date>2024-02-08T11:22:00Z</dc:date>
    </item>
    <item>
    <title>Badalona torna a il·lusionar-se amb el Memorial Li-Chang de màgia</title>
    <link>https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405540746</link>
    <description/>
    <pubDate>Thu, 08 Feb 2024 11:00:00 GMT</pubDate>
    <guid isPermaLink="false">https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405540746</guid>
    <dc:creator>MARIA GLORIA SANTAMARIA CASALS</dc:creator>
    <dc:date>2024-02-08T11:00:00Z</dc:date>
    </item>
    <item>
    <title>Lliurat el projecte de construcció de l’itinerari de vianants a la BV-1432 a Lliçà d’Amunt</title>
    <link>https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405538220</link>
    <description/>
    <pubDate>Thu, 08 Feb 2024 10:39:00 GMT</pubDate>
    <guid isPermaLink="false">https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405538220</guid>
    <dc:creator>EDGAR MATA ROCA</dc:creator>
    <dc:date>2024-02-08T10:39:00Z</dc:date>
    </item>
    <item>
    <title>La Diputació promou l’alta velocitat al territori a sis municipis de la província</title>
    <link>https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405413647</link>
    <description/>
    <pubDate>Wed, 07 Feb 2024 15:21:00 GMT</pubDate>
    <guid isPermaLink="false">https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405413647</guid>
    <dc:creator>EDGAR MATA ROCA</dc:creator>
    <dc:date>2024-02-07T15:21:00Z</dc:date>
    </item>
    <item>
    <title>El VII Festival Zero busca captivar el públic jove</title>
    <link>https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405406975</link>
    <description/>
    <pubDate>Wed, 07 Feb 2024 12:30:00 GMT</pubDate>
    <guid isPermaLink="false">https://www.diba.cat/web/sala-de-premsa/nota-de-premsa?p_p_id=56_INSTANCE_0MoY&p_p_lifecycle=0&refererPlid=390764&_56_INSTANCE_0MoY_groupId=553295&_56_INSTANCE_0MoY_articleId=405406975</guid>
    <dc:creator>MARIA GLORIA SANTAMARIA CASALS</dc:creator>
    <dc:date>2024-02-07T12:30:00Z</dc:date>
    </item>
    <item>
